[package]
name = "image-resize-lib-test"
version = "0.1.0"
authors = ["Brandon Clark <brandon.clark@leafgroup.com>"]

[[bin]]
name = "raster-resize"
path = "src/raster.rs"

[[bin]]
name = "image-resize"
path = "src/image.rs"

[dependencies]
raster = "0.2.0"
image = "0.19.0"